### ISSUE TITLE
Multiple Scenes

### ISSUE THREAD

**Issue by MichaelMiljanovic** [sqrlab/RobotON#43]
Have some

**Comment by KashifIV** [comment]
The following scenes have been created, they are all derived from when the camera had to move to a different part of the screen to achieve the "new scene" look. 

- Main Menu 
- newgame (the original scene now only containing the actual game) 
- Cinematic 
- Credits 

Note: Transitioning from Cinematic to newgame will take time due to the number of assets being loaded in.
